[package]
name = "wallet_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = "0.4.2"
hex = "0.4.3"
lazy_static = "1.5.0"
num-bigint = { version = "0.4.6", features = ["rand"] }
rand = "0.8.5"
rust-crypto = "0.2.36"
secp256k1 = "0.30.0"
sha3 = "0.10.8"
